# Generated by Django 3.0.8 on 2021-03-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
