# Generated by Django 3.0.8 on 2021-03-07 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vue_app', '0002_article_created_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_timestamp',
            new_name='timestamp',
        ),
    ]
