# Generated by Django 3.0.8 on 2021-03-07 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vue_app', '0003_auto_20210307_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='timestamp',
        ),
    ]
