# Generated by Django 3.1.7 on 2021-03-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_app', '0004_remove_article_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
